# Extra autostart processes
# exec-once = uwsm-app -- my-service
# Start GNOME keyring
exec-once = gnome-keyring-daemon --start --components=secrets,ssh

# Export keyring + Wayland env vars to systemd user session
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP SSH_AUTH_SOCK GNOME_KEYRING_CONTROL

